import random
import json
import os
from datetime import datetime

def get_sample_emails():
    # The sample emails are generated by ChatGPT 4o
    
    sample_emails = {
        "phishing": [
            {
                "from": "security@bank-secure-center.com",
                "subject": "URGENT: Your Account Has Been Compromised",
                "body": """
                Dear Valued Customer,
                
                We have detected suspicious activity on your account. Your account has been temporarily limited until you verify your information.
                
                Please click the link below to verify your identity and restore full access to your account:
                
                [Verify Account Now](https://banking-secure-verification.com/verify?account=12345)
                
                If you don't verify your account within 24 hours, your account will be permanently suspended.
                
                Regards,
                Security Team
                """
            },
            {
                "from": "paypal-support@secure-payments-center.com",
                "subject": "Payment Received - Action Required",
                "body": """
                Dear Customer,
                
                You have received a payment of $750.00 USD.
                
                This transaction requires your confirmation. Please log in to your account to confirm this payment:
                
                [Confirm Payment](https://paypaI-account-confirmation.com/login)
                
                This is an automated message. Please do not reply to this email.
                
                PayPaI Support Team
                """
            },
            {
                "from": "microsoft365@ms-verification-team.net",
                "subject": "Your Microsoft 365 subscription is expiring",
                "body": """
                Microsoft Account Alert:
                
                Your Microsoft 365 subscription is about to expire. To avoid service interruption, please update your billing information.
                
                [Update Billing Information](https://microsoft365-renewal.net/billing/update)
                
                Thank you for choosing Microsoft services.
                
                Microsoft Support Team
                © Microsoft Corporation
                """
            }
        ],
        "legitimate": [
            {
                "from": "newsletter@amazon.com",
                "subject": "Your Amazon Weekly Deals",
                "body": """
                Hello Amazon Customer,
                
                Check out this week's top deals:
                
                - 25% off on select electronics
                - Free shipping on orders over $25
                - Lightning deals on home appliances
                
                Visit amazon.com to see all deals.
                
                You are receiving this email because you're an Amazon customer.
                To unsubscribe, go to your email preferences in your account.
                
                © 2023 Amazon.com, Inc.
                """
            },
            {
                "from": "support@github.com",
                "subject": "GitHub Security Alert: New sign-in from an unrecognized device",
                "body": """
                Hi there,
                
                We noticed a recent sign-in to your GitHub account from a new device:
                
                Device: Chrome on Windows
                Location: San Francisco, CA, USA
                Time: September 15, 2023, 03:45 PM PDT
                
                If this was you, you can ignore this email.
                
                If you don't recognize this activity, please reset your password immediately:
                https://github.com/settings/security
                
                For more information, visit our help article on account security:
                https://docs.github.com/en/authentication/keeping-your-account-and-data-secure
                
                Thanks,
                The GitHub Team
                """
            },
            {
                "from": "no-reply@linkedin.com",
                "subject": "John Smith has sent you a connection request",
                "body": """
                John Smith wants to connect on LinkedIn
                
                Hi there,
                
                John Smith (Director of Engineering at Tech Company) has sent you a connection request.
                
                View profile: https://www.linkedin.com/in/john-smith-12345
                
                Accept connection: https://www.linkedin.com/invitations/view
                
                This email was sent to you by LinkedIn.
                © 2023 LinkedIn Corporation, 1000 W Maude Ave, Sunnyvale, CA 94085, USA
                """
            }
        ]
    }
    
    return sample_emails

def get_email_templates():
    
    templates = [
        {
            "name": "Bank Security Alert",
            "from_template": "security@{bank_domain}",
            "subject_template": "URGENT: Security Alert for Your {bank_name} Account",
            "body_template": """
            Dear Valued {bank_name} Customer,
            
            We have detected unusual activity on your {bank_name} account. For your security, we have temporarily limited access to sensitive account features.
            
            Please verify your identity by following this secure link:
            {verification_link}
            
            If you do not complete this verification within 24 hours, your account may be suspended.
            
            Regards,
            {bank_name} Security Team
            """
        },
        {
            "name": "Package Delivery Notification",
            "from_template": "notifications@{delivery_company}.com",
            "subject_template": "Your package #{tracking_number} requires attention",
            "body_template": """
            Delivery Notification
            
            Your package #{tracking_number} is pending delivery.
            
            Due to {issue_reason}, we need additional information to deliver your package.
            Please provide the required information by clicking here: {verification_link}
            
            Delivery Details:
            - Tracking Number: {tracking_number}
            - Expected Delivery: {delivery_date}
            - Address: {partial_address}
            
            Thank you,
            {delivery_company} Delivery Team
            """
        },
        {
            "name": "Tax Refund Notice",
            "from_template": "refunds@{tax_agency}.gov",
            "subject_template": "ACTION REQUIRED: {tax_year} Tax Refund Pending",
            "body_template": """
            {tax_agency} Refund Department
            
            Our records indicate that you are eligible for a tax refund of {refund_amount} for the {tax_year} tax year.
            
            To process your refund, please confirm your information:
            {verification_link}
            
            Refund processing will begin after verification and typically takes 3-5 business days.
            
            Regards,
            {tax_agency} Refund Department
            """
        },
        {
            "name": "Social Media Alert",
            "from_template": "security@{social_platform}.com",
            "subject_template": "Security Alert: New login to your {social_platform} account",
            "body_template": """
            Security Alert from {social_platform}
            
            We detected a new login to your account from:
            
            Device: {device_type}
            Location: {login_location}
            Time: {login_time}
            
            If this wasn't you, your account may be compromised.
            Secure your account immediately: {verification_link}
            
            The {social_platform} Security Team
            """
        }
    ]
    
    return templates

def generate_custom_phishing_email(template_name, variables):
    
    templates = get_email_templates()
    
    selected_template = None
    for template in templates:
        if template["name"] == template_name:
            selected_template = template
            break
    
    if not selected_template:
        return None
    
    from_address = selected_template["from_template"].format(**variables)
    subject = selected_template["subject_template"].format(**variables)
    body = selected_template["body_template"].format(**variables)
    
    return {
        "from": from_address,
        "subject": subject,
        "body": body
    }
